#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'simpleArraySum' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY ar as parameter.
#

def simpleArraySum(ar):
    # cara 1
    hasil_jumlah = 0
    or i in range(len(ar)):
        hasil_jumlah += ar [i]
    return hasil_jumlah 
    
    # cara 2
    return sum (ar)
    
    # cara 3 
    hasil_jumlah = 0
    for i in ar :
        hasil_jumlah += i
    return hasil_jumlah
        
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    ar_count = int(input().strip())

    ar = list(map(int, input().rstrip().split()))

    result = simpleArraySum(ar)

    fptr.write(str(result) + '\n')

    fptr.close()
